### PR TITLE
Fix ambiguos occurence of `controlT`

### PR DESCRIPTION
**Pull request by jsynacek**
Fixes: #73

### CODE REVIEW

**Comment by jsynacek** [comment]
See also https://github.com/scrive/hpqtypes/issues/30.

**Review by jonathanjouty — CHANGES_REQUESTED** [review]
CI fails.

**Comment by jonathanjouty** [comment]
Right, I think you need to publish https://github.com/scrive/hpqtypes/pull/31 first and bump the lower bound on `hpqtypes`

**Review by jonathanjouty — APPROVED** [review]
Code looks fine, pending CI green light.

**Pull request merged**
