### PR TITLE
Add a 'MonadUnliftIO' instance for 'LogT'

### PR DESCRIPTION
**Pull request by 23Skidoo**
Also since we're doing a major version bump anyway, rename a bunch of modules to follow the more widespread naming conventions.

### CODE REVIEW

**Comment by 23Skidoo** [comment]
I didn't bother bumping the version because #46 already takes care of that.

**Comment by 23Skidoo** [comment]
@arybczak OK. Otherwise you're fine with the new dependency?

**Comment by arybczak** [comment]
> you're fine with the new dependency?

Yeah, I think it's alright.

Thanks!

**Pull request merged**
