### PR TITLE
Fix compilation for new aeson-pretty + misc fixes

### PR DESCRIPTION
**Pull request by jonathanjouty**

### CODE REVIEW

**Comment by jonathanjouty** [comment]
Actually, version of `log` on Hackage is `0.5.2`.
I thought this was just due to Andrzej bumping maintainers list, but there are more differences which were never pushed here :/

Closing request as those should be pushed first.

**Comment by jonathanjouty** [comment]
**First merge changes here: https://github.com/scrive/log/pull/3**

Then I will fix conflicts so that this can be merged.

**Comment by jonathanjouty** [comment]
Rebased on branch `dev-jonathan-push-0.5.2`, so should merge cleanly after #3 is merged.

**Comment by mariuszrak** [comment]
Build for me on empty sandbox - if removed cabal.conf - with ghc-7.10.
Code looks find, same for other PR (https://github.com/scrive/log/pull/3)

**Comment by johanhil** [comment]
I also approve.

Den 18 jul 2016 16:43 skrev "mariuszrak" <notifications@github.com>:

**Comment by jonathanjouty** [comment]
Thank for @johanhil for the seal of approval 🐳

**Pull request merged**
